package app.otakureader.core.database.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Cached AniList metadata for a manga.
 *
 * Keyed by `mangaId` rather than autogenerated, so a refresh replaces the row instead of
 * accumulating versions — the same shape as [UpdateErrorEntity], and for the same reason: there is
 * exactly one current answer per manga and no value in a history.
 *
 * `ON DELETE CASCADE` because this metadata is meaningless once the manga is gone. Without it,
 * removing a manga from the library would leave a row keyed to an id that no longer exists, and
 * the table would grow for as long as the app is used.
 *
 * ### Tags are stored denormalized
 *
 * As two parallel `List<String>` columns — names, and ranks as strings — rather than a child table.
 * A child table would be the textbook answer, but the access pattern is "read every tag for this
 * manga, always together, never queried across manga", so a join buys nothing and costs a second
 * table plus its own cascade. The parallel-list encoding is the part to watch: the two lists must
 * stay the same length, which the mapper enforces by zipping and dropping any excess.
 */
@Entity(
    tableName = "manga_metadata",
    foreignKeys = [
        ForeignKey(
            entity = MangaEntity::class,
            parentColumns = ["id"],
            childColumns = ["mangaId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class MangaMetadataEntity(
    @PrimaryKey val mangaId: Long,
    val anilistId: Long,
    val description: String? = null,
    val bannerImage: String? = null,
    val coverImage: String? = null,
    val coverColor: String? = null,
    val genres: List<String> = emptyList(),
    val tagNames: List<String> = emptyList(),
    val tagRanks: List<String> = emptyList(),
    val averageScore: Int? = null,
    val popularity: Int? = null,
    val favourites: Int? = null,
    val format: String? = null,
    val countryOfOrigin: String? = null,
    val status: String? = null,
    val chapters: Int? = null,
    val startDate: String? = null,
    val endDate: String? = null,
    val synonyms: List<String> = emptyList(),
    val fetchedAt: Long = 0L,
)
