package app.otakureader.core.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

/**
 * Cached AniList metadata for a manga.
 *
 * Keyed by `mangaId` rather than autogenerated, so a refresh replaces the row instead of
 * accumulating versions — the same shape as [UpdateErrorEntity], and for the same reason: there is
 * exactly one current answer per manga and no value in a history.
 *
 * `ON DELETE CASCADE` because this metadata is meaningless once the manga is gone. Without it,
 * removing a manga from the library would leave a row keyed to an id that no longer exists.
 *
 * That cascade is also the whole of the reclamation story, which is why there is no TTL sweep: one
 * row per manga, deleted with the manga, so the table is bounded by the library rather than by how
 * long the app has been used. An earlier draft carried a `deleteOlderThan` for a maintenance worker
 * and a comment calling it the thing that "prevents indefinite growth" — nothing called it, and the
 * growth it claimed to prevent could not happen.
 *
 * ### Tags are stored denormalized
 *
 * As two parallel `List<String>` columns — names, and ranks as strings — rather than a child table.
 * A child table would be the textbook answer, but the access pattern is "read every tag for this
 * manga, always together, never queried across manga", so a join buys nothing and costs a second
 * table plus its own cascade. The parallel-list encoding is the part to watch: the two lists must
 * stay the same length, which the mapper enforces by zipping and dropping any excess.
 */
@Entity(
    tableName = "manga_metadata",
    foreignKeys = [
        ForeignKey(
            entity = MangaEntity::class,
            parentColumns = ["id"],
            childColumns = ["mangaId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class MangaMetadataEntity(
    @PrimaryKey val mangaId: Long,
    val anilistId: Long,
    val description: String? = null,
    val bannerImage: String? = null,
    val coverImage: String? = null,
    val coverColor: String? = null,
    val genres: List<String> = emptyList(),
    val tagNames: List<String> = emptyList(),
    val tagRanks: List<String> = emptyList(),
    val averageScore: Int? = null,
    val popularity: Int? = null,
    val favourites: Int? = null,
    val format: String? = null,
    val countryOfOrigin: String? = null,
    val status: String? = null,
    val chapters: Int? = null,
    val startDate: String? = null,
    val endDate: String? = null,
    val synonyms: List<String> = emptyList(),
    /**
     * Cast and credits, as JSON rather than parallel columns. See `DatabaseConverters`.
     *
     * `defaultValue` is declared, not just written into the migration's `ALTER TABLE`. Room
     * compares the default it expects from the entity against the one it reads back from SQLite,
     * so a default that exists only in the migration is a schema mismatch — and one that surfaces
     * only on upgrade, never on a fresh install.
     */
    @ColumnInfo(defaultValue = "[]")
    val characters: List<StoredPerson> = emptyList(),
    @ColumnInfo(defaultValue = "[]")
    val staff: List<StoredPerson> = emptyList(),
    @ColumnInfo(defaultValue = "[]")
    val relations: List<StoredRelation> = emptyList(),
    @ColumnInfo(defaultValue = "[]")
    val externalLinks: List<StoredExternalLink> = emptyList(),
    val fetchedAt: Long = 0L,
)

/**
 * The stored form of a person, kept apart from the domain `MangaMetadataPerson`.
 *
 * Serialized field names are a persisted format: renaming one here silently stops old rows
 * deserializing. Putting `@Serializable` on the domain model instead would hand that constraint to
 * a class whose whole job is to be free of storage concerns, and would make an ordinary domain
 * rename a data-compatibility decision. The mapping between the two costs a few lines and keeps
 * the coupling somewhere it is visible.
 */
@Serializable
data class StoredPerson(
    val id: Long,
    val name: String,
    val imageUrl: String? = null,
    val role: String? = null,
)

/**
 * The stored form of a related manga. Kept apart from the domain model for the reason
 * [StoredPerson] is — serialized field names are a persisted format, and the domain layer should
 * not have to treat a rename as a data-compatibility decision.
 */
@Serializable
data class StoredRelation(
    val anilistId: Long,
    val title: String,
    val coverImage: String? = null,
    val format: String? = null,
    val relationType: String? = null,
)

/** The stored form of an off-site link. */
@Serializable
data class StoredExternalLink(
    val url: String,
    val site: String,
)
