package app.otakureader.core.database.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * One scored recommendation, rebuilt wholesale by `RecommendationWorker`.
 *
 * ### Why the key is an autogenerated id
 *
 * `mangaId` was the primary key, which quietly required every recommendation to be a manga already
 * in the local database. That held while the only candidates were rows seeded from a source's
 * popular list. It stops holding the moment AniList's own "readers of this also liked" edges are a
 * channel: those name a media id on AniList and nothing local, so they have no `mangaId` to be
 * keyed by.
 *
 * So [mangaId] and [sourceId] are nullable and [anilistId] joins them. Exactly one of `mangaId` and
 * `anilistId` identifies any given row — a local candidate has the former, an AniList edge the
 * latter — and both are set when a local manga was matched to AniList, which is what lets the
 * two channels deduplicate against each other.
 *
 * The unique indices are what make that deduplication real rather than intended: without them the
 * same title arriving from both channels would simply be inserted twice. They are partial in
 * effect rather than declaration — SQLite treats NULLs as distinct, so rows lacking one id do not
 * collide on it.
 *
 * ### [genresJson] carries the explanation
 *
 * The column already existed and the domain model ignored it. It now holds the tags the
 * recommendation was matched on, so the carousel can say *why* a title is being suggested rather
 * than presenting it as an oracle.
 */
@Entity(
    tableName = "manga_feature_cache",
    indices = [
        Index(value = ["mangaId"], unique = true),
        Index(value = ["anilistId"], unique = true),
    ],
)
data class RecommendationEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val mangaId: Long? = null,
    val anilistId: Long? = null,
    val title: String,
    val thumbnailUrl: String?,
    val sourceId: Long? = null,
    val genresJson: String,
    val score: Float,
    val lastComputed: Long,
)
