package app.otakureader.core.database.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * The most recent library-update failure for a manga. Keyed by mangaId (not autogenerated) so a
 * new failure replaces the previous one rather than accumulating a history — matches Komikku's
 * "current unresolved errors" model. Cleared when the manga next updates successfully.
 */
@Entity(
    tableName = "update_errors",
    foreignKeys = [
        ForeignKey(
            entity = MangaEntity::class,
            parentColumns = ["id"],
            childColumns = ["mangaId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class UpdateErrorEntity(
    @PrimaryKey val mangaId: Long,
    val errorMessage: String,
    val timestamp: Long,
)
