package app.otakureader.domain.model

import androidx.compose.runtime.Immutable
import kotlinx.serialization.Serializable

/**
 * Represents a manga recommendation generated by AI.
 *
 * @property mangaId The ID of the recommended manga (if in library/db)
 * @property title The title of the recommended manga
 * @property author The author of the manga
 * @property thumbnailUrl URL to the manga cover image
 * @property description Brief description of the manga
 * @property genres List of genres for the manga
 * @property sourceId The source to find this manga from
 * @property sourceUrl The URL to access this manga from the source
 * @property reasonExplanation AI-generated explanation of why this manga is recommended
 * @property confidenceScore AI confidence score (0.0 to 1.0)
 * @property basedOnMangaIds IDs of user's manga that influenced this recommendation
 * @property basedOnGenres Genres from user's history that influenced this recommendation
 * @property recommendationType Type of recommendation (e.g., similar, discovery, trending)
 * @property generatedAt Timestamp when the recommendation was generated
 */
@Immutable
@Serializable
data class MangaRecommendation(
    val mangaId: Long? = null,
    val title: String,
    val author: String? = null,
    val thumbnailUrl: String? = null,
    val description: String? = null,
    val genres: List<String> = emptyList(),
    val sourceId: String,
    val sourceUrl: String,
    val reasonExplanation: String,
    val confidenceScore: Float = 0.0f,
    val basedOnMangaIds: List<Long> = emptyList(),
    val basedOnGenres: List<String> = emptyList(),
    val recommendationType: RecommendationType = RecommendationType.SIMILAR,
    val generatedAt: Long = System.currentTimeMillis()
)

/**
 * Types of AI recommendations.
 */
@Serializable
enum class RecommendationType {
    /** Based on similar manga the user has enjoyed */
    SIMILAR,
    
    /** Discovery - manga outside user's usual preferences but potentially interesting */
    DISCOVERY,
    
    /** Trending manga in genres the user enjoys */
    TRENDING,
    
    /** Based on specific themes/tropes the user likes */
    THEME_BASED,
    
    /** Based on favorite authors/artists */
    AUTHOR_BASED,
    
    /** Hidden gem - less known manga matching user's taste */
    HIDDEN_GEM
}

/**
 * User reading patterns extracted from their history.
 * Used as input for AI recommendations.
 *
 * @property favoriteGenres Genres the user reads most frequently
 * @property favoriteAuthors Authors the user follows
 * @property preferredStatus Preferred manga status (ongoing, completed, etc.)
 * @property averageReadingTime Average time spent per manga
 * @property preferredChapterCountMin Minimum preferred manga length based on reading patterns
 * @property preferredChapterCountMax Maximum preferred manga length based on reading patterns
 * @property commonThemes Extracted themes from manga descriptions
 * @property readingVelocity How quickly the user reads through series
 */
@Immutable
@Serializable
data class UserReadingPattern(
    val favoriteGenres: List<GenrePreference> = emptyList(),
    val favoriteAuthors: List<AuthorPreference> = emptyList(),
    val preferredStatus: List<MangaStatus> = emptyList(),
    val averageReadingTimeMs: Long = 0L,
    val preferredChapterCountMin: Int? = null,
    val preferredChapterCountMax: Int? = null,
    val commonThemes: List<String> = emptyList(),
    val readingVelocity: ReadingVelocity = ReadingVelocity.MODERATE,
    val favoriteTropes: List<String> = emptyList()
)

/**
 * Genre preference with weight based on engagement.
 */
@Immutable
@Serializable
data class GenrePreference(
    val genre: String,
    val frequency: Int,
    val averageTimeSpentMs: Long,
    val completionRate: Float
)

/**
 * Author preference with engagement metrics.
 */
@Immutable
@Serializable
data class AuthorPreference(
    val author: String,
    val mangaCount: Int,
    val totalTimeSpentMs: Long
)

/**
 * Reading velocity classification.
 */
@Serializable
enum class ReadingVelocity {
    SLOW,      // Takes time, savors content
    MODERATE,  // Normal reading pace
    FAST,      // Binges quickly
    BINGER     // Completes series very quickly
}

/**
 * Result of a recommendation request.
 *
 * @property recommendations List of manga recommendations
 * @property pattern The reading pattern used to generate recommendations
 * @property refreshedAt When the recommendations were last refreshed
 * @property expiresAt When the recommendations expire and should be refreshed
 * @property isCached Whether these are cached results
 */
@Immutable
@Serializable
data class RecommendationResult(
    val recommendations: List<MangaRecommendation>,
    val pattern: UserReadingPattern? = null,
    val refreshedAt: Long = System.currentTimeMillis(),
    val expiresAt: Long = System.currentTimeMillis() + DEFAULT_CACHE_DURATION_MS,
    val isCached: Boolean = false
) {
    companion object {
        const val DEFAULT_CACHE_DURATION_MS = 7L * 24 * 60 * 60 * 1000 // 7 days
    }
}

/**
 * Input data for generating recommendations.
 *
 * @property libraryManga User's favorited manga
 * @property readingHistory History of chapters read
 * @property timeSpentPerManga Time spent reading each manga
 * @property ratings User ratings for manga (if available)
 */
@Immutable
@Serializable
data class RecommendationInput(
    val libraryManga: List<MangaWithEngagement>,
    val readingHistory: List<ChapterWithHistory>,
    val totalReadingTimeMs: Long = 0L
)

/**
 * Manga with engagement metrics for recommendation input.
 */
@Immutable
@Serializable
data class MangaWithEngagement(
    val manga: Manga,
    val chaptersRead: Int = 0,
    val timeSpentMs: Long = 0L,
    val isCompleted: Boolean = false,
    val completionPercentage: Float = 0f
)
